# .github/workflows/deploy-branches.yml

name: Deploy GitHub Pages from Multiple Branches

on:
  push:
    branches:
      - main
      - sandbox
      - lkg
  workflow_dispatch:  # Allows manual triggering

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  # Build job for the Main branch
  build-main:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Main Branch
        uses: actions/checkout@v3
        with:
          ref: main
          
      - name: Setup Pages
        uses: actions/configure-pages@v3
        
      - name: Upload Main Branch Artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: '.'
          
  # Build job for the Sandbox branch
  build-sandbox:
    if: github.ref == 'refs/heads/sandbox'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Sandbox Branch
        uses: actions/checkout@v3
        with:
          ref: sandbox
          
      - name: Create output directory
        run: mkdir -p _site/sandbox
        
      - name: Copy Sandbox files to subfolder
        run: cp -r ./* _site/sandbox/ 2>/dev/null || true
        
      - name: Create Sandbox index page
        run: |
          cat > _site/sandbox/index.html << EOF
          <!DOCTYPE html>
          <html>
          <head>
            <meta charset="UTF-8">
            <meta http-equiv="refresh" content="0; url=./index.html">
            <title>Redirecting...</title>
          </head>
          <body>
            <p>This is the Sandbox environment. Redirecting to the main page...</p>
            <script>
              window.location.href = "./index.html";
            </script>
          </body>
          </html>
          EOF
          
      - name: Upload Sandbox Artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: '_site'
          
  # Build job for the LKG branch
  build-lkg:
    if: github.ref == 'refs/heads/lkg'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout LKG Branch
        uses: actions/checkout@v3
        with:
          ref: lkg
          
      - name: Create output directory
        run: mkdir -p _site/lkg
        
      - name: Copy LKG files to subfolder
        run: cp -r ./* _site/lkg/ 2>/dev/null || true
        
      - name: Create LKG index page
        run: |
          cat > _site/lkg/index.html << EOF
          <!DOCTYPE html>
          <html>
          <head>
            <meta charset="UTF-8">
            <meta http-equiv="refresh" content="0; url=./index.html">
            <title>Redirecting...</title>
          </head>
          <body>
            <p>This is the LKG (Last Known Good) environment. Redirecting to the main page...</p>
            <script>
              window.location.href = "./index.html";
            </script>
          </body>
          </html>
          EOF
          
      - name: Upload LKG Artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: '_site'

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: [build-main, build-sandbox, build-lkg]
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
